#!/usr/bin/env bash
#

set -Eeuo pipefail


if command -v delta >/dev/null 2>&1; then
  exec delta "${@}"
fi

if command -v diff-so-fancy >/dev/null 2>&1 && command -v less >/dev/null 2>&1; then
  exec "${BASH}" -o pipefail -c 'diff-so-fancy "$@" | less --tabs=4 -RFX' bash "${@}"
fi

if command -v less >/dev/null 2>&1; then
  exec less "${@}"
fi

echo "Couldn't find any of the following pagers: delta, diff-so-fancy + less, less" >&2
exit 1
