#!/usr/bin/env bash
#
# Create a bash file using strict mode
#

#set -euxo pipefail
set -euo pipefail

display_usage () {
    echo 'Create a bash script using strict mode'
    echo 'Usage: bskel <path>'
}
# Bail out early
if [[ ( $# -gt 2 ) || ( $# -eq 0) ]]; then
    display_usage
    exit 1
fi

# Read CLI arguments using getopt
cli_options=$(getopt -o th --long help -- "$@")
[ $? -eq 0 ] || {
    echo "Incorrect options provided"
    exit 1
}
eval set -- "$cli_options"

# default values
path=''

# Parse getopt arguments
while true; do
    case "$1" in
        -h | --help )           display_usage
                                exit 0
                                ;;
        --)                     shift;
                                path="${1}";
                                break;;
    esac
done

touch "${path}"
echo '#!/usr/bin/env bash' >> "${path}"
echo '#' >> "${path}"
echo '' >> "${path}"
echo 'set -xeuo pipefail' >> "${path}"
chmod +x "${path}"
