#!/usr/bin/env bash
#
# [docker] exec into a running container
#

#set -euxo pipefail
set -euo pipefail


if [ ! -z $1 ]
then
    cmd="${2:-'/bin/bash'}"
    docker exec -it $1 "${cmd}"
else
    echo 'Please provide a running container!'
fi
