#!/usr/bin/env bash
#
# docker-get-container-id
# Give the container name and get the container's id.
# If no name is specified, return the most recent container.
#

#set -euxo pipefail
set -o pipefail

if [ ! -z  $1 ]
then
    docker ps | grep $1 | awk '{print $1}'
else
    docker ps -q | head -n1
fi
