#!/usr/bin/env bash
#
# https://stackoverflow.com/questions/19104847/how-to-generate-a-dockerfile-from-an-image

set -xeuo pipefail

docker history --no-trunc $1 | tac | tr -s ' ' | cut -d " " -f 5- | sed 's,^/bin/sh -c #(nop) ,,g' | sed 's,^/bin/sh -c,RUN,g' | sed 's, && ,\n  & ,g' | sed 's,\s*[0-9]*[\.]*[0-9]*[kMG]*B\s*$,,g' | head -n -1
