#!/usr/bin/env bash
#
# test docker image
#

#set -euxo pipefail
set -euo pipefail

proxy_vars='-e ftp_proxy -e http_proxy -e https_proxy -e no_proxy -e rsync_proxy -e FTP_PROXY -e HTTP_PROXY -e HTTPS_PROXY -e NO_PROXY -e RSYNC_PROXY'

if [ -z $1 ]
then
    echo 'Usage: dtest IMG [CMD]'
    echo
    echo 'This is the equivalent of "docker run --rm -it <IMG> <CMD>"'
    echo 'If CMD is not specified, it defaults to /bin/bash'
else
    image="${1}"
    cmd="${2:-/bin/bash}"
    docker run --rm -it ${proxy_vars} ${image} "${cmd}"
fi
