#!/usr/bin/env bash


# Usage:
#
#    source init_conda
#

# Return true or false if we are on BDAP
is_bdap() {
  grep -q jeodpp /etc/hostname
}

# https://stackoverflow.com/questions/54913218/detect-whether-running-on-azure-iaas-vm-net-application
# https://stackoverflow.com/questions/50629815/quickly-detect-if-vm-is-running-on-azure
# https://learn.microsoft.com/en-us/azure/security/fundamentals/azure-domains
is_azure () {
  grep -q cloudapp /etc/resolv.conf
}

if which micromamba; then
  MAMBA_EXE=$(which micromamba)
  if is_bdap; then
    MAMBA_ROOT_PREFIX="${MAMBA_ROOT_PREFIX:-/scratch/$(whoami)/.micromamba}"
  elif is_azure; then
    MAMBA_ROOT_PREFIX="${MAMBA_ROOT_PREFIX:-/mnt/micromamba}"
  else
    MAMBA_ROOT_PREFIX="${MAMBA_ROOT_PREFIX:-"${HOME}"/.micromamba}"
  fi
  echo "mamba exe at   : ${MAMBA_EXE}"
  echo "mamba prefix at: ${MAMBA_ROOT_PREFIX}"
  mkdir -p "${MAMBA_ROOT_PREFIX}"
  export MAMBA_EXE
  export MAMBA_ROOT_PREFIX
  eval "$(micromamba shell hook)"
  # Since micromamba is not installing the conda and the mamba binaries,
  # let's pretend that we have them!
  conda() { micromamba "${@}"; }
  mamba() { micromamba "${@}"; }
elif [ -f /opt/miniconda3/etc/profile.d/conda.sh ]; then
  echo 'Found conda in /opt/miniconda3'
  source /opt/miniconda3/etc/profile.d/conda.sh
elif [ -f "${HOME}"/miniconda3/etc/profile.d/conda.sh ]; then
  echo "Found conda in ${HOME}/miniconda3"
  source "${HOME}"/miniconda3/etc/profile.d/conda.sh
elif [ -f /opt/miniconda/etc/profile.d/conda.sh ]; then
  echo 'Found conda in /opt/miniconda'
  source /opt/miniconda/etc/profile.d/conda.sh
elif [ -f "${HOME}"/miniconda/etc/profile.d/conda.sh ]; then
  echo "Found conda in ${HOME}/miniconda"
  source "${HOME}"/miniconda/etc/profile.d/conda.sh
elif [ -f /mnt/mambaforge/etc/profile.d/conda.sh ]; then
  echo "Found conda in /mnt/mambaforge"
  source /mnt/mambaforge/etc/profile.d/conda.sh
else
  echo "Couldn't find conda."
  return 1
fi
