#!/usr/bin/env bash


# Usage:
#
#    source init_conda
#

if [[ $(which micromamba) ]]; then
  MAMBA_EXE=$(which micromamba)
  MAMBA_ROOT_PREFIX="${HOME}"/.micromamba
  echo "Found micromamba at: ${MAMBA_EXE}"
  mkdir -p "${MAMBA_ROOT_PREFIX}"
  export MAMBA_EXE
  export MAMBA_ROOT_PREFIX
  eval "$(micromamba shell hook)"
  conda() { micromamba "${@}"; }
  mamba() { micromamba "${@}"; }
elif [ -f /opt/miniconda3/etc/profile.d/conda.sh ]; then
  echo 'Found conda in /opt/miniconda3'
  source /opt/miniconda3/etc/profile.d/conda.sh
elif [ -f "${HOME}"/miniconda3/etc/profile.d/conda.sh ]; then
  echo "Found conda in ${HOME}/miniconda3"
  source "${HOME}"/miniconda3/etc/profile.d/conda.sh
elif [ -f /opt/miniconda/etc/profile.d/conda.sh ]; then
  echo 'Found conda in /opt/miniconda'
  source /opt/miniconda/etc/profile.d/conda.sh
elif [ -f "${HOME}"/miniconda/etc/profile.d/conda.sh ]; then
  echo "Found conda in ${HOME}/miniconda"
  source "${HOME}"/miniconda/etc/profile.d/conda.sh
elif [ -f /mnt/mambaforge/etc/profile.d/conda.sh ]; then
  echo "Found conda in /mnt/mambaforge"
  source /mnt/mambaforge/etc/profile.d/conda.sh
else
  echo "Couldn't find conda."
  return 1
fi
