#!/usr/bin/env bash
#

set -Eeuo pipefail

declare -r notification="${*}"
declare webhook_path
declare webhook_url

webhook_path=~/.config/my_notifications/debug
readonly webhook_path

display_usage () {
    echo 'Send a DEBUG notification to Slack'
    echo 'Usage: ndebug <NOTIFICATION_TEXT>'
}

# Bail out early
if [[ $# -eq 0 ]]; then
    display_usage
    exit 1
fi

if [[ ! -f "${webhook_path}" && -r "${webhook_path}" ]]; then
  printf 'Path does not exist or it is not readable: %s\n' "${webhook_path}"
  exit 2
fi

webhook_url="$(<"${webhook_path}")"
readonly webhook_url

curl \
  --fail \
  --silent \
  --show-error \
  -X POST \
  -H 'Content-type: application/json' \
  --data "{\"text\":\"${notification[*]}\"}" \
  "${webhook_url}" \
  > /dev/null
