#!/usr/bin/env bash
#
# Custom tree command for python projects
#

#set -euxo pipefail
set -euo pipefail

tree -C -v --dirsfirst -P '*.py|*.toml|*.ini|*.cfg|*.yaml|*.yml|*.xml|*.conf|*.json|*.html|*.jinja|*.j2' -I '*__pycache__|*.pyc' "$@"
